version: '3'

services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=analog
      - POSTGRES_USER=analog
      - POSTGRES_PASSWORD=analog
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db